title: I-Café
email: iveta@i-cafe.at
phone: 0043 677 62502262
opening_time: Mo 8:30 - 17:00; Di-Fr 8:00 - 17:00
address: Hauptstraße 32, Grödig
description: Ein neues Café in der Nähe von Salzburg. Kaffee, Kuchen, Frühstück, Jause. Alles lecker und vegan freundlich!
baseurl: ''
url: 'https://www.i-cafe.at'
twitter_username: jekyllrb
github_username: jekyll
instagram_username: i_cafe_at
facebook_username: i.cafe.at
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
    sass_dir: _sass
    style: compressed
permalink: /:title
