title: I-Café
email: iveta@i-cafe.at
phone: 0043 677 62502262
opening_time: Mo-Fr 6:00 - 16:00
address: Hauptstraße 32, Grödig
description: Ein kleines Steh-Café in der Nähe von Salzburg. Kaffee, Kuchen, Frühstück, Jause. Alles lecker! Und vegan freundlich!
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
instagram_username: i_cafe_at
facebook_username: I-Café-713785282160566
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
    sass_dir: _sass
    style: compressed
